# Generated by Django 5.1.5 on 2025-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('editorial_summary', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('types', models.JSONField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('current_opening_hours', models.JSONField(blank=True, null=True)),
                ('formatted_address', models.CharField(blank=True, max_length=300, null=True)),
                ('formatted_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('vicinity', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
