# Generated by Django 5.1.5 on 2025-01-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_googleplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_id', models.CharField(max_length=255)),
                ('lieu_name', models.CharField(max_length=255)),
                ('lieu_proche_id', models.CharField(max_length=255)),
                ('lieu_proche_name', models.CharField(max_length=255)),
                ('similitude', models.FloatField()),
            ],
        ),
    ]
